# Generated by Django 4.1.4 on 2022-12-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('option_one', models.CharField(max_length=120)),
                ('option_two', models.CharField(max_length=120)),
                ('option_three', models.CharField(blank=True, max_length=120)),
                ('option_four', models.CharField(blank=True, max_length=120)),
                ('answer', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.section_test')),
            ],
        ),
    ]
